apiVersion: v1
kind: Service
metadata:
  name: azkaban-headless
  namespace: data-platform
  labels:
    app: azkaban
spec:
  clusterIP: None
  ports:
  - port: 8081
    name: azkaban-web-ui
  selector:
    app: azkaban
