apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-config
  namespace: data-platform
data:
  jvm.heap: "128M"
  tick: "2000"
  init: "10"
  sync: "5"
  client.cnxns: "60"
  snap.retain: "3"
  purge.interval: "0"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-budget
  namespace: data-platform
spec:
  selector:
    matchLabels:
      app: zk
  minAvailable: 2
