apiVersion: v1
kind: Service
metadata:
  name: zk-headless
  namespace: data-platform
  labels:
    app: zk-headless
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-server-headless
  namespace: data-platform
  labels:
    app: zk-headless
spec:
  ports:
  - port: 2181
    name: zk-api
  clusterIP: None
  selector:
    app: zk
