apiVersion: v1
kind: Service
metadata:
  name: drelephant-headless
  namespace: data-platform
  labels:
    app: drelephant
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: drelephant-web-ui
  selector:
    app: drelephant
